language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=7db887541ba6df3075e3a6ead2456b0ddf6bee65969308191c62afe1ea461566"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "gulp ci"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "iojs-v1"
  - "iojs-v2"
cache:
  directories:
    - 'node_modules'
